### PR TITLE
Prod var env

### PR DESCRIPTION
**Pull request by jtmst**
Move token value to inline, env not loading for client components after build

### CODE REVIEW

**Comment by nonprofittechy** [comment]
@colarusso can you confirm we can set a referer restriction for SPOT such that it's fine to include the API key here in the source? It's what we did before...

**Comment by colarusso** [comment]
We actually don't have a referrer restriction in place. All the live implementations aside from courtformsonline keep it hidden. We got away with it in the source there just because. :/ Also, the demo keys that are public are throttled.

**Comment by jtmst** [comment]
> We actually don't have a referrer restriction in place. All the live implementations aside from courtformsonline keep it hidden. We got away with it in the source there just because. :/ Also, the demo keys that are public are throttled.

There isnt a great way to hide these without putting some kind of server in place since its all static output.  Even if its tucked in a ENV file its still visible to anyone looking at the request from their browser.

**Comment by nonprofittechy** [comment]
> Agreed. Another consequence of this is the site cobbled together during the pandemic.

@colarusso how feasible is it to add referer restrictions to the API keys for SPOT?

**Review by nonprofittechy — APPROVED** [review]
I'm good with merging for now--I think we need to fix upstream as in a static site the API key will always be visible.

**Pull request merged**
